// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkxiMWn8MNCNA6FhrV2bmyaGnKVyqgjtI',
    appId: '1:56218069405:web:5cf57b521d1ecc2c5fa774',
    messagingSenderId: '56218069405',
    projectId: 'appcamera-f2f57',
    authDomain: 'appcamera-f2f57.firebaseapp.com',
    storageBucket: 'appcamera-f2f57.appspot.com',
    measurementId: 'G-ZPTH9R7BE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpzpYaivLPPXSnZjnqWwJhQvO3IM-ppDA',
    appId: '1:56218069405:android:cfc8f11976417ae45fa774',
    messagingSenderId: '56218069405',
    projectId: 'appcamera-f2f57',
    storageBucket: 'appcamera-f2f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vhdk17wdrHWfUYn2762Xji8ax54-ppI',
    appId: '1:56218069405:ios:0a7ab85155ea82c45fa774',
    messagingSenderId: '56218069405',
    projectId: 'appcamera-f2f57',
    storageBucket: 'appcamera-f2f57.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vhdk17wdrHWfUYn2762Xji8ax54-ppI',
    appId: '1:56218069405:ios:1e976f294502aefa5fa774',
    messagingSenderId: '56218069405',
    projectId: 'appcamera-f2f57',
    storageBucket: 'appcamera-f2f57.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
